# Generated by Django 6.0.6 on 2026-07-04 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('farmer', 'Farmer'), ('buyer', 'Buyer')], max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('district', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('farm_size', models.CharField(blank=True, max_length=100)),
                ('main_crop', models.CharField(blank=True, max_length=100)),
                ('business_name', models.CharField(blank=True, max_length=100)),
                ('buying_interest', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
