# Generated by Django 6.0.6 on 2026-07-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='crop_status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold')], default='available', max_length=20),
        ),
    ]
