# Generated by Django 6.0.3 on 2026-07-17 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0003_weatheralert_recentactivity'),
        ('Pages', '0006_crop_crop_status'),
    ]

    operations = [
    ]
